import type { SerializeOptions } from "../../../integrations/serialize/serialize.types.ts";
import { isUserDefinedTypeSchema, stableId } from "../../utils.ts";
import type { Table } from "../table.model.ts";
import { CreateTableChange } from "./table.base.ts";

/**
 * Create a table.
 *
 * @see https://www.postgresql.org/docs/17/sql-createtable.html
 *
 * Synopsis
 * ```sql
 * CREATE [ [ GLOBAL | LOCAL ] { TEMPORARY | TEMP } | UNLOGGED ] TABLE [ IF NOT EXISTS ] table_name ( [
 *   { column_name data_type [ COLLATE collation ] [ column_constraint [ ... ] ]
 *     | table_constraint
 *     | LIKE source_table [ like_option ... ] }
 *     [, ... ]
 * ] )
 * [ INHERITS ( parent_table [, ... ] ) ]
 * [ PARTITION BY { RANGE | LIST | HASH } ( { column_name | ( expression ) } [, ... ] ) ]
 * [ USING method ]
 * [ WITH ( storage_parameter [= value] [, ... ] ) | WITHOUT OIDS ]
 * [ ON COMMIT { PRESERVE ROWS | DELETE ROWS | DROP } ]
 * [ TABLESPACE tablespace_name ]
 * ```
 */
export class CreateTable extends CreateTableChange {
  public readonly table: Table;
  public readonly scope = "object" as const;

  constructor(props: { table: Table }) {
    super();
    this.table = props.table;
  }

  get creates() {
    return [
      this.table.stableId,
      ...this.table.columns.map((col) =>
        stableId.column(this.table.schema, this.table.name, col.name),
      ),
    ];
  }

  get requires() {
    const dependencies = new Set<string>();

    // Schema dependency
    dependencies.add(stableId.schema(this.table.schema));

    // Owner dependency
    dependencies.add(stableId.role(this.table.owner));

    // Parent table dependency (for inheritance or partitioning)
    if (this.table.parent_schema && this.table.parent_name) {
      dependencies.add(
        stableId.table(this.table.parent_schema, this.table.parent_name),
      );
    }

    // Column type dependencies (user-defined types only)
    for (const col of this.table.columns) {
      if (
        col.is_custom_type &&
        col.custom_type_schema &&
        col.custom_type_name
      ) {
        dependencies.add(
          stableId.type(col.custom_type_schema, col.custom_type_name),
        );
      }

      // Collation dependency (if non-default)
      if (col.collation) {
        // Collations are stored as schema-qualified strings like "public.collation_name"
        // Note: The collation string may be quoted, so we need to handle that
        const unquotedCollation = col.collation.replace(/^"|"$/g, "");
        const collationParts = unquotedCollation.split(".");
        if (collationParts.length === 2) {
          const [collationSchema, collationName] = collationParts;
          if (isUserDefinedTypeSchema(collationSchema)) {
            dependencies.add(
              stableId.collation(collationSchema, collationName),
            );
          }
        }
      }

      // Function dependencies from DEFAULT expressions are handled by pg_depend
      // catalog constraints in the sort pipeline, which provides exact argument
      // types and covers all expression contexts (not just column defaults).
    }

    return Array.from(dependencies);
  }

  serialize(_options?: SerializeOptions): string {
    const parts: string[] = ["CREATE"];

    // Add TEMPORARY/UNLOGGED based on persistence
    if (this.table.persistence === "t") {
      parts.push("TEMPORARY");
    } else if (this.table.persistence === "u") {
      parts.push("UNLOGGED");
    }

    parts.push("TABLE");

    // Add schema and name
    parts.push(`${this.table.schema}.${this.table.name}`);

    // If this is a partition (child) table, emit PARTITION OF ... FOR VALUES ...
    if (
      this.table.parent_schema &&
      this.table.parent_name &&
      this.table.partition_bound
    ) {
      const columnOverrides = this.table.columns
        .filter((col) => col.is_generated && col.default)
        .map(
          (col) => `${col.name} GENERATED ALWAYS AS (${col.default}) STORED`,
        );
      return [
        ...parts,
        "PARTITION OF",
        `${this.table.parent_schema}.${this.table.parent_name}`,
        ...(columnOverrides.length > 0
          ? [`(${columnOverrides.join(", ")})`]
          : []),
        this.table.partition_bound,
      ].join(" ");
    }

    // Add columns definition
    if (this.table.columns.length === 0) {
      parts.push("()");
    } else {
      const columnDefinitions = this.table.columns.map((col) => {
        const tokens: string[] = [];

        // Column name
        tokens.push(col.name);

        // Data type (use formatted type string from the catalog)
        tokens.push(col.data_type_str);

        // Collation
        if (col.collation) {
          tokens.push("COLLATE", col.collation);
        }

        // Identity / generated / default
        if (col.is_identity) {
          tokens.push(
            col.is_identity_always
              ? "GENERATED ALWAYS AS IDENTITY"
              : "GENERATED BY DEFAULT AS IDENTITY",
          );
        } else if (col.is_generated && col.default) {
          // Generated stored columns expose their expression via pg_attrdef
          tokens.push(`GENERATED ALWAYS AS (${col.default}) STORED`);
        } else if (col.default) {
          tokens.push("DEFAULT", col.default);
        }

        // Nullability
        if (col.not_null) {
          tokens.push("NOT NULL");
        }

        return tokens.join(" ");
      });

      parts.push(`(${columnDefinitions.join(", ")})`);
    }

    // Add INHERITS if parent table exists (non-partition inheritance only)
    if (
      this.table.parent_schema &&
      this.table.parent_name &&
      !this.table.partition_bound
    ) {
      parts.push(
        "INHERITS",
        `(${this.table.parent_schema}.${this.table.parent_name})`,
      );
    }

    // Add PARTITION BY if this is a partitioned table (parent)
    if (this.table.partition_by) {
      parts.push("PARTITION BY", this.table.partition_by);
    }

    // Add storage parameters if specified
    if (this.table.options && this.table.options.length > 0) {
      parts.push("WITH", `(${this.table.options.join(", ")})`);
    }

    return parts.join(" ");
  }
}
